feat : Query optimization
frappe/press pull request #1942
Opened 2024-07-11 14:16 UTC by arunmathaisk

The below screenshots will give you an idea what this feature is all about.
The ability to create database indexes based on suggested indexes .

<img width="1249" alt="image" src="https://github.com/frappe/press/assets/61804369/73635dc3-8aa1-4f8e-b436-0158d8520fb1">

<img width="1217" alt="image" src="https://github.com/frappe/press/assets/61804369/98f2fc10-6a6b-4570-96fb-9c314fe94e01">

<img width="1122" alt="image" src="https://github.com/frappe/press/assets/61804369/62aca002-ac12-4f21-955b-30359cbe2445">

<img width="1040" alt="image" src="https://github.com/frappe/press/assets/61804369/05f44f3d-2f9a-4ebc-bc43-20644ef5665b">

<img width="1122" alt="image" src="https://github.com/frappe/press/assets/61804369/62ba139a-eb90-40e4-8c5d-68211ecc1bb0">

<img width="1430" alt="image" src="https://github.com/frappe/press/assets/61804369/eb7171c7-c93a-446f-ba82-1170ea313916">
<img width="1229" alt="image" src="https://github.com/frappe/press/assets/61804369/1cc9d82b-e4b3-4e72-b472-57bc88819d60">

2024-07-12 05:46 UTC, BreadGenie requested changes

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue
> +				<span class="pr-2">Count: {{ count}}</span> -->
let's remove this if it's not used?

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue
> +				<div v-if="sucesfullyCreatedIndexJob === true">
typo

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue
> +					</Dialog>
so whenever we do an action (a job is created in this context), we show it using a toast instead of a dialog and reroute the user to the jobs page

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SiteMariaDBSlowQueryDialog.vue
> +				No query index suggestions available 😕. Try adding indexes manually 🤷‍♂️
let's avoid emojis 😄

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SitePerformance.vue
> +		/>
ideally we shouldn't be showing this banner, instead we can give them docs like we have done in https://github.com/frappe/press/blob/7f7a26d1a19f57b8554578b18562967f89842c09/dashboard/src2/objects/tabs/patches.js#L21

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/components/site/SitePerformance.vue
> +<script lang="jsx">
```suggestion
<script>
```

Since we aren't using any jsx here

2024-07-12 05:46 UTC, BreadGenie commented on dashboard/src2/objects/site.js
> +
```suggestion
```

nitpick

2024-07-12 07:10 UTC, arunmathaisk commented
@BreadGenie  thanks for the review man. will fix them rn.

2024-07-16 10:52 UTC, merged

2024-09-09 14:57 UTC, BreadGenie commented on dashboard/src2/components/site/SitePerformance.vue
> +			};
```
const formatDateTime = date => {
		return this.$dayjs(date)
			.format('YYYY-MM-DD HH:mm:ss');
};
```
ref: https://day.js.org/docs/en/display/format