Dynamic app logos
frappe/press pull request #1967
Opened 2024-07-17 14:26 UTC by saurabh6790

2024-07-17 14:41 UTC, BreadGenie commented on dashboard/src/views/partials/LoginBox.vue
> +			<BrandLogo :footer="1" />
not very explicit with using 1
```suggestion
			<BrandLogo :footer="true" />
```

2024-07-18 14:31 UTC, BreadGenie requested changes
A minor change needed. Otherwise looks good.

2024-07-18 14:31 UTC, BreadGenie commented on dashboard/src2/components/BrandLogo.vue
> +	props: ['header', 'footer'],
on 2nd thought this should've been a type prop with options being header and footer. Take a look at [AlertBanner.vue](https://github.com/frappe/press/blob/master/dashboard/src2/components/AlertBanner.vue) file

Then we can do
```
<BrandLogo type="header" />
```

2024-07-30 03:36 UTC, rmehta commented
PR description, screenshots? @saurabh6790 - This is not 2014!

2024-08-14 06:37 UTC, closed without merging